### ISSUE TITLE
Support transaction >= 1.5

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.sqlalchemy#20]
Newer versions fail with some errors, see #17

**Comment by mmerickel** [comment]
Just to be clear, have you seen any actual problems with this package in production or just with the tests? I've been happily using zope.sqlalchemy with transaction 2.0 since it came out. Also the package doesn't appear to use any of the parts of the api that changed. This issue is purely about the test suite and thus it would be silly to pin the entire package.

**Comment by icemac** [comment]
@mmerickel I did not see any problems in while using this package. But a package without successfully running tests is considered to be broken. The known broken tests (might) shadow actual broken code.
I do not propose to release a version of this package with the contrainted `transaction` version but green tests are a necessary starting point for every work on any package. 

Sorry, I currently have neither the energy nor knowledge to fix the tests. You are heartily welcome to fix this issue.

**Comment by drnextgis** [comment]
I've made a PR https://github.com/zopefoundation/zope.sqlalchemy/pull/25, please check it out.

**Comment by drnextgis** [comment]
PR is merged, issue can be closed.
