### ISSUE TITLE
Link to Zope Transactions Outdated

### ISSUE THREAD

**Issue by lucas993** [zopefoundation/zope.sqlalchemy#27]
`src/zope/sqlalchemy/README.rst` should link to `http://www.zodb.org/en/latest/#transactions` rather than `http://www.zodb.org/zodbbook/transactions.html`

**Comment by jamadden** [comment]
The docs on www.zodb.org come from [zopefoundation/ZODB](https://github.com/zopefoundation/ZODB/tree/master/doc) and have been edited recently (although there are a [number of issues open for improvements](https://github.com/zopefoundation/ZODB/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) ). The docs at zodb.readthedocs.io come from [a different repository](https://github.com/cguardia/ZODB-Documentation/) that hasn't been updated since 2015. Prominent people [have expressed concerns](https://github.com/cguardia/ZODB-Documentation/issues/18) about those docs. 

Perhaps this would be a good time to address https://github.com/zopefoundation/ZODB/issues/107 and create/update the transactions document in zopefoundation/ZODB.
