### ISSUE TITLE
Add support for SQLAlchemy 2.x

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.sqlalchemy#76]
Currently tests fail when running against 2.x, so we have to pin SQLAlchemy to < 2 for now.

See #64 as preparation for this issue.

**Comment by hoonhout** [comment]
@icemac I forked this repo to test if our application landscape is compatible with SQLA 2.0. It appears that I now have a draft PR ready that makes the tests for this package compatible with SQLA 2.0 as described in #64. It currently resides in our fork (https://github.com/VanOord/zope.sqlalchemy/pull/1), but I'm happy to make a proper PR if interested.

**Comment by icemac** [comment]
@hoonhout A PR for SQLAlchemy 2 compatibility would be very helpful.

Please notice beforehand: According to the contributing policies of the zopefoundation organization you need to sign a contributor agreement before any non-trivial change can be merged. For details please consult the [Contributing guidelines for zopefoundation projects](https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md).

**Comment by olemoign** [comment]
This issue is preventing my company from migrating to SQLAlchemy 2.x, is there anything I can do to help?

**Comment by icemac** [comment]
@hoonhout As you have already created a draft PR, is there a way to help to get it into the main repository?

**Comment by bouillon** [comment]
It would be nice somebody can upgrade the package on pypi we need it to get the possibility to migrate to sqlalchemy 2

**Comment by icemac** [comment]
@bouillon Creating a release is not enough, at first the package has to be ported to support SQLAlchemy >= 2 (e. g. see the warnings presented in #64). Any help is appreciated.

**Comment by Daverball** [comment]
I created a PR: https://github.com/zopefoundation/zope.sqlalchemy/pull/79

There's really not much that needed to be changed.

**Comment by bouillon** [comment]
Something blocks from merge?

**Comment by Daverball** [comment]
The issues on the CI have been ironed out, so for now I am just waiting on a review, which will happen when it will happen. You can install version 1.6 with SQLAlchemy 2.0 in the meantime, it didn't have the pin to prevent it from being installed along with SQLAlchemy 2.0 yet. I already have it running that way on multiple projects in production without issue.

There were no code changes necessary in the actual production code, it's just the tests that needed to be updated. (Although if you want to switch to the new psycopg v3 backend in SQLAlchemy that won't work properly with 1.6, since the transaction will not be retried on serialization errors, I added support for that as part of my pull request as well, since we would like to switch to that)

**Comment by bouillon** [comment]
Thanks for reply. Yeas I run it also like you say on some projects. For some other I need an official package on pypi. Let's wait than.

**Comment by bouillon** [comment]
thanks for this explanations
